### ISSUE TITLE
Проблема типизации аргумента

### ISSUE THREAD

**Issue by orymonin** [IvanMartynovLETI/MatrixOperations#3]
https://github.com/IvanMartynovLETI/MatrixOperations/blob/b4aa3f1191f9e5ec57fea829c9ee43cd86691747/src/com/test/MatrixPackage/MatrixMethods.java#L4

Размерность матрицы определяется целым числом. Немного странно требовать строку для определения размерности матрицы

**Comment by IvanMartynovLETI** [comment]
Я предполагал, что пользователь может быть не совсем адекватен. Просто на работе меня учили проектировать аппаратуру так, чтобы пользоваться ей можно было с глубокого перепоя/не приходя в сознание/в измененном состоянии сознания когда пользователь, мягко говоря, не совсем адекватен. Ошибки пользователя не должны иметь глобальных последствий. Именно из этих соображений я задавал размерность матрицы строковым типом.

**Comment by orymonin** [comment]
Пользователь может быть неадекватным, но проблема разбора его неадекватности должна лежать на плечах блока, который связывает ввод от пользователя с бизнес-логикой

**Comment by orymonin** [comment]
Задав размерность строкой ты вынуждаешь качественные модули, которые хотят воспользоваться твоим кодом конвертировать целое число к строке

**Comment by IvanMartynovLETI** [comment]
Понял, спасибо!
