### ISSUE TITLE
Некрасивая работа со строками

### ISSUE THREAD

**Issue by orymonin** [IvanMartynovLETI/MatrixOperations#8]
https://github.com/IvanMartynovLETI/MatrixOperations/blob/08141c04b0b88a750aae5e15225db32dab790d76/src/com/test/matrix/classes/flip/FlipHorizontally.java#L19-L22

Нет никакого смысла так оформлять строки.
Можно просто написать
```        
return "int[][] flipMethod(int[][] inputMatrix) method of FlipHorizontally class returns matrix, \n" +
            "flipped horizontally, inputMatrix must be a square matrix \n";
```

**Comment by IvanMartynovLETI** [comment]
Учту на будущее, спасибо!
